name: "Blackbird-FL8"
description: "Checks Go files for common errors using go vet"
author: "Ryan Mello"
inputs: {}
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_WORKSPACE: ${{ github.workspace }}
  args:
    - ${{ github.workspace }}
branding:
  icon: "box"
  color: "black"
