name: "Blackbird-007"
description: "Checks Go files for common errors using go vet"
author: "Ryan Mello"
inputs: {}
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "box"
  color: "black"
