name: Blackbird

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  fly:
    name: Fly Blackbird
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fly Blackbird
        uses: ./
