name: Blackbird

on:
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
  push:
    branches: [main]
    paths:
      - "go.mod"
      - "go.sum"

jobs:
  fly:
    name: Fly Blackbird
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fly Blackbird
        uses: ./
